# Generating Final Tables and Figures

In [15]:
import os
import pandas as pd
import glob
import shutil

### Move tables to ../outputs/tables/raw

In [14]:
raw_dir = "../outputs/tables/raw"
final_dir = "../outputs/tables/final"

os.makedirs(raw_dir, exist_ok=True)
os.makedirs(final_dir, exist_ok=True)

In [16]:
base_dir = "../outputs/tables"

files_to_move = glob.glob(os.path.join(base_dir, "*.csv"))
if not files_to_move:
    print("No CSV files found in the base directory to move.")
else:
    for file_path in files_to_move:
        file_name = os.path.basename(file_path)
        dest_path = os.path.join(raw_dir, file_name)
        
        # Move the file
        shutil.move(file_path, dest_path)
        print(f"Moved: {file_name} -> outputs/tables/raw/")

Moved: anova_tests_by_tier_income_q.csv -> outputs/tables/raw/
Moved: baseline_model.csv -> outputs/tables/raw/
Moved: conditional_summary_by_tier_high_black_zip.csv -> outputs/tables/raw/
Moved: conditional_summary_by_tier_income_q.csv -> outputs/tables/raw/
Moved: mean_median_differences_by_tier_high_black_zip.csv -> outputs/tables/raw/
Moved: model_with_protected_variables.csv -> outputs/tables/raw/
Moved: model_with_protected_variables_borough.csv -> outputs/tables/raw/
Moved: pairwise_q1_vs_q4_tests_by_tier_income_q.csv -> outputs/tables/raw/
Moved: pairwise_tests_by_tier_high_black_zip.csv -> outputs/tables/raw/

Anova Tests Table

In [20]:
anova_test_table = pd.read_csv("../outputs/tables/raw/anova_tests_by_tier_income_q.csv")
anova_test_table

  severity_tier  anova_p_value
0          High   3.970286e-20
1        Medium   8.311508e-72
2           Low  2.790289e-218

In [42]:
anova_test_table.columns = ["Severity Tier", "ANOVA p-value"]
anova_test_table

  Severity Tier  ANOVA p-value
0          High   3.970286e-20
1        Medium   8.311508e-72
2           Low  2.790289e-218

In [43]:
output_path = "../outputs/tables/final/anova_tests_by_tier_income_q.csv"
anova_test_table.to_csv(output_path, index=False)

Baseline Model

In [76]:
baseline_model = pd.read_csv("../outputs/tables/raw/baseline_model.csv")
baseline_model

,Unnamed: 0,coef,std_err,t,p_value
0,Intercept,399.204636,6.722325,59.384907,0.000000e+00
1,C(hour)[T.1],17.179441,8.161967,2.104816,3.530799e-02
2,C(hour)[T.2],20.150078,8.516650,2.365963,1.798377e-02
3,C(hour)[T.3],61.115765,8.783272,6.958200,3.452266e-12
4,C(hour)[T.4],61.006202,8.989635,6.786283,1.152347e-11
5,C(hour)[T.5],80.243372,9.126357,8.792487,1.469037e-18
6,C(hour)[T.6],151.710092,8.826742,17.187552,3.496313e-66
7,C(hour)[T.7],128.496666,8.296994,15.487135,4.410012e-54
8,C(hour)[T.8],138.258888,7.721873,17.904838,1.160750e-71
9,C(hour)[T.9],124.783883,7.383129,16.901220,4.663080e-64
10,C(hour)[T.10],110.783968,7.297410,15.181272,4.882224e-52
11,C(hour)[T.11],150.801068,7.258142,20.776813,7.979916e-96
12,C(hour)[T.12],173.431267,7.248451,23.926665,2.026975e-126
13,C(hour)[T.13],204.377508,7.258789,28.155869,3.130792e-174
14,C(hour)[T.14],258.565083,7.225520,35.784978,5.838647e-280
15,C(hour)[T.15],341.281937,7.238738,47.146606,0.000000e+00
16,C(hour)[T.16],356.001614,7.278051,48.914416,0.000000e+00
17,C(hour)[T.17],401.382594,7.292805,55.038164,0.000000e+00
18,C(hour)[T.18],411.548422,7.305774,56.331942,0.000000e+00
19,C(hour)[T.19],223.971400,7.316777,30.610665,1.615317e-205
20,C(hour)[T.20],101.254871,7.375028,13.729422,6.936305e-43
21,C(hour)[T.21],42.081174,7.458471,5.642064,1.681476e-08
22,C(hour)[T.22],20.661017,7.577145,2.726755,6.396363e-03
23,C(hour)[T.23],6.322683,7.795363,0.811083,4.173188e-01
24,C(day_of_week)[T.1],-62.743562,3.930900,-15.961628,2.473622e-57
25,C(day_of_week)[T.2],-19.616193,3.923143,-5.000122,5.732053e-07
26,C(day_of_week)[T.3],-23.182311,3.922708,-5.909772,3.428858e-09
27,C(day_of_week)[T.4],-27.539202,3.903799,-7.054462,1.735772e-12
28,C(day_of_week)[T.5],-147.248937,3.973095,-37.061516,4.283714e-300
29,C(day_of_week)[T.6],-155.953640,4.002541,-38.963658,0.000000e+00
30,C(severity_tier_numeric)[T.2],151.581746,2.826587,53.627122,0.000000e+00
31,C(severity_tier_numeric)[T.3],435.064331,2.718708,160.026111,0.000000e+00
32,C(borough)[T.BROOKLYN],-53.724830,2.962595,-18.134380,1.838639e-73
33,C(borough)[T.MANHATTAN],17.361086,3.079531,5.637575,1.725889e-08
34,C(borough)[T.QUEENS],-124.976419,3.194338,-39.124352,0.000000e+00
35,C(borough)[T.RICHMOND / STATEN ISLAND],-220.120531,5.632643,-39.079442,0.000000e+00

In [77]:
baseline_model.columns = ["Predictors", "Coefficient", "Standard Error", "t", "p-value"]

In [78]:
baseline_model["Predictors"] = ["Intercept", "1 AM", "2 AM", "3 AM", "4 AM", "5 AM", "6 AM", "7 AM", "8 AM", "9 AM", "10 AM", "11 AM", "12 PM", "1 PM", "2 PM", "3 PM", "4 PM", "5 PM", "6 PM", "7 PM", "8 PM", "9 PM", "10 PM", "11 PM", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Severity Level: Medium", "Severity Level: Low", "Brooklyn", "Hanhattan", "Queens", "Richmond / Staten Island"]

In [79]:
baseline_model

,Predictors,Coefficient,Standard Error,t,p-value
0,Intercept,399.204636,6.722325,59.384907,0.000000e+00
1,1 AM,17.179441,8.161967,2.104816,3.530799e-02
2,2 AM,20.150078,8.516650,2.365963,1.798377e-02
3,3 AM,61.115765,8.783272,6.958200,3.452266e-12
4,4 AM,61.006202,8.989635,6.786283,1.152347e-11
5,5 AM,80.243372,9.126357,8.792487,1.469037e-18
6,6 AM,151.710092,8.826742,17.187552,3.496313e-66
7,7 AM,128.496666,8.296994,15.487135,4.410012e-54
8,8 AM,138.258888,7.721873,17.904838,1.160750e-71
9,9 AM,124.783883,7.383129,16.901220,4.663080e-64
10,10 AM,110.783968,7.297410,15.181272,4.882224e-52
11,11 AM,150.801068,7.258142,20.776813,7.979916e-96
12,12 PM,173.431267,7.248451,23.926665,2.026975e-126
13,1 PM,204.377508,7.258789,28.155869,3.130792e-174
14,2 PM,258.565083,7.225520,35.784978,5.838647e-280
15,3 PM,341.281937,7.238738,47.146606,0.000000e+00
16,4 PM,356.001614,7.278051,48.914416,0.000000e+00
17,5 PM,401.382594,7.292805,55.038164,0.000000e+00
18,6 PM,411.548422,7.305774,56.331942,0.000000e+00
19,7 PM,223.971400,7.316777,30.610665,1.615317e-205
20,8 PM,101.254871,7.375028,13.729422,6.936305e-43
21,9 PM,42.081174,7.458471,5.642064,1.681476e-08
22,10 PM,20.661017,7.577145,2.726755,6.396363e-03
23,11 PM,6.322683,7.795363,0.811083,4.173188e-01
24,Monday,-62.743562,3.930900,-15.961628,2.473622e-57
25,Tuesday,-19.616193,3.923143,-5.000122,5.732053e-07
26,Wednesday,-23.182311,3.922708,-5.909772,3.428858e-09
27,Thursday,-27.539202,3.903799,-7.054462,1.735772e-12
28,Friday,-147.248937,3.973095,-37.061516,4.283714e-300
29,Saturday,-155.953640,4.002541,-38.963658,0.000000e+00
30,Severity Level: Medium,151.581746,2.826587,53.627122,0.000000e+00
31,Severity Level: Low,435.064331,2.718708,160.026111,0.000000e+00
32,Brooklyn,-53.724830,2.962595,-18.134380,1.838639e-73
33,Hanhattan,17.361086,3.079531,5.637575,1.725889e-08
34,Queens,-124.976419,3.194338,-39.124352,0.000000e+00
35,Richmond / Staten Island,-220.120531,5.632643,-39.079442,0.000000e+00

In [80]:
output_path = "../outputs/tables/final/baseline_model.csv"
baseline_model.to_csv(output_path, index=False)

For the above, mention 12 AM, Sunday, Severity Level: High, and Bronx are the reference. They are left out of the model due to collinearity issues.

Conditional Summary by Tier High Black Zip

In [48]:
cond_summ_high_black = pd.read_csv("../outputs/tables/raw/conditional_summary_by_tier_high_black_zip.csv")
cond_summ_high_black

  severity_tier  high_black_zip      n        mean  median         std
0          High               0  42358  444.339109   384.0  313.162513
1          High               1  44212  479.640256   416.0  344.618963
2           Low               0  74571  827.403870   587.0  796.933589
3           Low               1  77693  959.819984   668.0  914.619407
4        Medium               0  67175  587.958496   459.0  495.457342
5        Medium               1  57474  649.047378   502.0  554.338197

In [63]:
cond_summ_high_black.columns = ["Severity Tier", "High Black Population ZIP (Yes = 1)", "n", "Mean", "Median", "Std. Dev"]
severity_order = ['High', 'Medium', 'Low']
cond_summ_high_black['Severity Tier'] = pd.Categorical(cond_summ_high_black['Severity Tier'], categories=severity_order, ordered=True)
cond_summ_high_black_sorted = cond_summ_high_black.sort_values(by=['Severity Tier', 'High Black Population ZIP (Yes = 1)'])
cond_summ_high_black_sorted

,Severity Tier,High Black Population ZIP (Yes = 1),n,Mean,Median,Std. Dev
0,High,0,42358,444.339109,384.0,313.162513
1,High,1,44212,479.640256,416.0,344.618963
4,Medium,0,67175,587.958496,459.0,495.457342
5,Medium,1,57474,649.047378,502.0,554.338197
2,Low,0,74571,827.403870,587.0,796.933589
3,Low,1,77693,959.819984,668.0,914.619407

In [64]:
output_path = "../outputs/tables/final/conditional_summary_by_tier_high_black_zip.csv"
cond_summ_high_black_sorted.to_csv(output_path, index=False)

Conditional summary by Tier Income

In [52]:
cond_summ_income = pd.read_csv("../outputs/tables/raw/conditional_summary_by_tier_income_q.csv")
cond_summ_income

   severity_tier income_q      n        mean  median         std
0           High   Q1_low  22117  475.389339   408.0  357.301888
1           High       Q2  22031  466.444238   399.0  345.022544
2           High       Q3  21676  457.828981   406.0  287.668062
3           High  Q4_high  20012  445.586898   385.0  323.015122
4         Medium   Q1_low  28797  653.998264   499.0  579.019116
5         Medium       Q2  30190  623.800132   476.0  542.950808
6         Medium       Q3  31032  582.886375   473.0  446.816069
7         Medium  Q4_high  32044  594.812726   460.0  514.083208
8            Low   Q1_low  40117  990.839619   664.0  975.126174
9            Low       Q2  37253  920.881754   640.0  885.062271
10           Low       Q3  37079  808.140673   610.0  710.409125
11           Low  Q4_high  36766  850.691046   593.0  830.581895

In [54]:
cond_summ_income.columns = ["Severity Tier", "Income Quartile", "n", "Mean", "Median", "Std. Dev"]
cond_summ_income["Income Quartile"] = ["Q1 (Low)", "Q2", "Q3", "Q4 (High)"] * 3
cond_summ_income

   Severity Tier Income Quartile      n        Mean  Median    Std. Dev
0           High        Q1 (Low)  22117  475.389339   408.0  357.301888
1           High              Q2  22031  466.444238   399.0  345.022544
2           High              Q3  21676  457.828981   406.0  287.668062
3           High       Q4 (High)  20012  445.586898   385.0  323.015122
4         Medium        Q1 (Low)  28797  653.998264   499.0  579.019116
5         Medium              Q2  30190  623.800132   476.0  542.950808
6         Medium              Q3  31032  582.886375   473.0  446.816069
7         Medium       Q4 (High)  32044  594.812726   460.0  514.083208
8            Low        Q1 (Low)  40117  990.839619   664.0  975.126174
9            Low              Q2  37253  920.881754   640.0  885.062271
10           Low              Q3  37079  808.140673   610.0  710.409125
11           Low       Q4 (High)  36766  850.691046   593.0  830.581895

In [56]:
output_path = "../outputs/tables/final/conditional_summary_by_tier_income_q.csv"
cond_summ_income.to_csv(output_path, index=False)

Mean Median Differences by Tier High Black Zip

In [57]:
mean_med_diff_high_black_zip = pd.read_csv("../outputs/tables/raw/mean_median_differences_by_tier_high_black_zip.csv")
mean_med_diff_high_black_zip

,severity_tier,mean_difference_highBlack_minus_lowBlack_seconds,median_difference_highBlack_minus_lowBlack_seconds
0,High,35.301147,32.0
1,Low,132.416114,81.0
2,Medium,61.088881,43.0

In [58]:
mean_med_diff_high_black_zip.columns

Index(['severity_tier', 'mean_difference_highBlack_minus_lowBlack_seconds',
       'median_difference_highBlack_minus_lowBlack_seconds'],
      dtype='object')

In [67]:
mean_med_diff_high_black_zip.columns = ["Severity Tier", "Mean Difference: High vs. Low Black ZIP (seconds)", "Median Difference: High vs. Low Black ZIP (seconds)"]
mean_med_diff_high_black_zip['Severity Tier'] = pd.Categorical(mean_med_diff_high_black_zip['Severity Tier'], categories=severity_order, ordered=True)
mean_med_diff_high_black_zip_sorted = mean_med_diff_high_black_zip.sort_values(by=["Severity Tier"])
mean_med_diff_high_black_zip_sorted

,Severity Tier,Mean Difference: High vs. Low Black ZIP (seconds),Median Difference: High vs. Low Black ZIP (seconds)
0,High,35.301147,32.0
2,Medium,61.088881,43.0
1,Low,132.416114,81.0

In [69]:
output_path = "../outputs/tables/final/mean_median_differences_by_tier_high_black_zip.csv"
mean_med_diff_high_black_zip_sorted.to_csv(output_path, index=False)

Model with Protected Variables Borough

In [75]:
model_borough = pd.read_csv("../outputs/tables/raw/model_with_protected_variables_borough.csv")
model_borough

,Unnamed: 0,coef,std_err,t,p_value
0,Intercept,87.465079,1.694989,51.602160,0.000000e+00
1,C(hour)[T.1],17.179441,8.161967,2.104816,3.530799e-02
2,C(hour)[T.2],20.150078,8.516650,2.365963,1.798377e-02
3,C(hour)[T.3],61.115765,8.783272,6.958200,3.452266e-12
4,C(hour)[T.4],61.006202,8.989635,6.786283,1.152347e-11
5,C(hour)[T.5],80.243372,9.126357,8.792487,1.469037e-18
6,C(hour)[T.6],151.710092,8.826742,17.187552,3.496313e-66
7,C(hour)[T.7],128.496666,8.296994,15.487135,4.410012e-54
8,C(hour)[T.8],138.258888,7.721873,17.904838,1.160750e-71
9,C(hour)[T.9],124.783883,7.383129,16.901220,4.663080e-64
10,C(hour)[T.10],110.783968,7.297410,15.181272,4.882224e-52
11,C(hour)[T.11],150.801068,7.258142,20.776813,7.979916e-96
12,C(hour)[T.12],173.431267,7.248451,23.926665,2.026975e-126
13,C(hour)[T.13],204.377508,7.258789,28.155869,3.130792e-174
14,C(hour)[T.14],258.565083,7.225520,35.784978,5.838647e-280
15,C(hour)[T.15],341.281937,7.238738,47.146606,0.000000e+00
16,C(hour)[T.16],356.001614,7.278051,48.914416,0.000000e+00
17,C(hour)[T.17],401.382594,7.292805,55.038164,0.000000e+00
18,C(hour)[T.18],411.548422,7.305774,56.331942,0.000000e+00
19,C(hour)[T.19],223.971400,7.316777,30.610665,1.615317e-205
20,C(hour)[T.20],101.254871,7.375028,13.729422,6.936305e-43
21,C(hour)[T.21],42.081174,7.458471,5.642064,1.681476e-08
22,C(hour)[T.22],20.661017,7.577145,2.726755,6.396363e-03
23,C(hour)[T.23],6.322683,7.795363,0.811083,4.173188e-01
24,C(day_of_week)[T.1],-62.743562,3.930900,-15.961628,2.473622e-57
25,C(day_of_week)[T.2],-19.616193,3.923143,-5.000122,5.732053e-07
26,C(day_of_week)[T.3],-23.182311,3.922708,-5.909772,3.428858e-09
27,C(day_of_week)[T.4],-27.539202,3.903799,-7.054462,1.735772e-12
28,C(day_of_week)[T.5],-147.248937,3.973095,-37.061516,4.283714e-300
29,C(day_of_week)[T.6],-155.953640,4.002541,-38.963658,0.000000e+00
30,C(severity_tier_numeric)[T.2],151.581746,2.826587,53.627122,0.000000e+00
31,C(severity_tier_numeric)[T.3],435.064331,2.718708,160.026111,0.000000e+00
32,C(borough)[T.BROOKLYN],-77.456212,2.428298,-31.897326,5.927625e-223
33,C(borough)[T.MANHATTAN],89.424306,2.378468,37.597437,9.342467e-309
34,C(borough)[T.QUEENS],-22.875193,2.268808,-10.082473,6.652304e-24
35,C(borough)[T.RICHMOND / STATEN ISLAND],-119.875170,3.627630,-33.045038,4.162222e-239
36,C(high_black_borough)[T.1],140.791136,2.152977,65.393699,0.000000e+00
37,median_income_borough,0.002188,0.000058,37.734334,0.000000e+00
38,pct_white_borough,-28.755115,0.820486,-35.046422,1.246992e-268
39,pct_black_borough,40.936375,0.682840,59.950204,0.000000e+00
40,pct_hispanic_borough,104.936677,1.847405,56.802204,0.000000e+00

In [81]:
model_borough.columns = ["Predictors", "Coefficient", "Standard Error", "t", "p-value"]
model_borough["Predictors"] = ["Intercept", "1 AM", "2 AM", "3 AM", "4 AM", "5 AM", "6 AM", "7 AM", "8 AM", "9 AM", "10 AM", "11 AM", "12 PM", "1 PM", "2 PM", "3 PM", "4 PM", "5 PM", "6 PM", "7 PM", "8 PM", "9 PM", "10 PM", "11 PM", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Severity Level: Medium", "Severity Level: Low", "Brooklyn", "Hanhattan", "Queens", "Richmond / Staten Island", "High Black (Borough)", "Median Income (Borough)", "White Percent (Borough)", "Black Percent (Borough)", "Hispanic Percent (Borough)"]
model_borough

,Predictors,Coefficient,Standard Error,t,p-value
0,Intercept,87.465079,1.694989,51.602160,0.000000e+00
1,1 AM,17.179441,8.161967,2.104816,3.530799e-02
2,2 AM,20.150078,8.516650,2.365963,1.798377e-02
3,3 AM,61.115765,8.783272,6.958200,3.452266e-12
4,4 AM,61.006202,8.989635,6.786283,1.152347e-11
5,5 AM,80.243372,9.126357,8.792487,1.469037e-18
6,6 AM,151.710092,8.826742,17.187552,3.496313e-66
7,7 AM,128.496666,8.296994,15.487135,4.410012e-54
8,8 AM,138.258888,7.721873,17.904838,1.160750e-71
9,9 AM,124.783883,7.383129,16.901220,4.663080e-64
10,10 AM,110.783968,7.297410,15.181272,4.882224e-52
11,11 AM,150.801068,7.258142,20.776813,7.979916e-96
12,12 PM,173.431267,7.248451,23.926665,2.026975e-126
13,1 PM,204.377508,7.258789,28.155869,3.130792e-174
14,2 PM,258.565083,7.225520,35.784978,5.838647e-280
15,3 PM,341.281937,7.238738,47.146606,0.000000e+00
16,4 PM,356.001614,7.278051,48.914416,0.000000e+00
17,5 PM,401.382594,7.292805,55.038164,0.000000e+00
18,6 PM,411.548422,7.305774,56.331942,0.000000e+00
19,7 PM,223.971400,7.316777,30.610665,1.615317e-205
20,8 PM,101.254871,7.375028,13.729422,6.936305e-43
21,9 PM,42.081174,7.458471,5.642064,1.681476e-08
22,10 PM,20.661017,7.577145,2.726755,6.396363e-03
23,11 PM,6.322683,7.795363,0.811083,4.173188e-01
24,Monday,-62.743562,3.930900,-15.961628,2.473622e-57
25,Tuesday,-19.616193,3.923143,-5.000122,5.732053e-07
26,Wednesday,-23.182311,3.922708,-5.909772,3.428858e-09
27,Thursday,-27.539202,3.903799,-7.054462,1.735772e-12
28,Friday,-147.248937,3.973095,-37.061516,4.283714e-300
29,Saturday,-155.953640,4.002541,-38.963658,0.000000e+00
30,Severity Level: Medium,151.581746,2.826587,53.627122,0.000000e+00
31,Severity Level: Low,435.064331,2.718708,160.026111,0.000000e+00
32,Brooklyn,-77.456212,2.428298,-31.897326,5.927625e-223
33,Hanhattan,89.424306,2.378468,37.597437,9.342467e-309
34,Queens,-22.875193,2.268808,-10.082473,6.652304e-24
35,Richmond / Staten Island,-119.875170,3.627630,-33.045038,4.162222e-239
36,High Black (Borough),140.791136,2.152977,65.393699,0.000000e+00
37,Median Income (Borough),0.002188,0.000058,37.734334,0.000000e+00
38,White Percent (Borough),-28.755115,0.820486,-35.046422,1.246992e-268
39,Black Percent (Borough),40.936375,0.682840,59.950204,0.000000e+00
40,Hispanic Percent (Borough),104.936677,1.847405,56.802204,0.000000e+00

In [82]:
output_path = "../outputs/tables/final/model_with_protected_variables_borough.csv"
model_borough.to_csv(output_path, index=False)

Model with Protected Variables

In [83]:
model = pd.read_csv("../outputs/tables/raw/model_with_protected_variables.csv")
model

,Unnamed: 0,coef,std_err,t,p_value
0,Intercept,206.163649,11.960451,17.237113,1.487709e-66
1,C(hour)[T.1],19.529311,8.177713,2.388114,1.693560e-02
2,C(hour)[T.2],21.761760,8.526913,2.552127,1.070717e-02
3,C(hour)[T.3],62.793767,8.802166,7.133899,9.774769e-13
4,C(hour)[T.4],62.140589,9.015552,6.892599,5.487182e-12
5,C(hour)[T.5],79.358833,9.152281,8.670935,4.303224e-18
6,C(hour)[T.6],151.148118,8.872062,17.036414,4.677624e-65
7,C(hour)[T.7],129.638154,8.329836,15.563110,1.350907e-54
8,C(hour)[T.8],139.888649,7.743290,18.065789,6.385675e-73
9,C(hour)[T.9],127.692992,7.400898,17.253716,1.116494e-66
10,C(hour)[T.10],113.965386,7.311407,15.587339,9.250719e-55
11,C(hour)[T.11],155.047400,7.273738,21.316054,9.307467e-101
12,C(hour)[T.12],177.398343,7.265929,24.415094,1.515164e-131
13,C(hour)[T.13],208.279441,7.276076,28.625241,5.205478e-180
14,C(hour)[T.14],263.482059,7.246028,36.362275,5.672124e-289
15,C(hour)[T.15],345.950813,7.259738,47.653345,0.000000e+00
16,C(hour)[T.16],360.543389,7.300167,49.388376,0.000000e+00
17,C(hour)[T.17],406.644280,7.314319,55.595647,0.000000e+00
18,C(hour)[T.18],416.480243,7.329631,56.821444,0.000000e+00
19,C(hour)[T.19],227.883861,7.336313,31.062450,1.481564e-211
20,C(hour)[T.20],104.205915,7.394035,14.093241,4.296816e-45
21,C(hour)[T.21],43.515537,7.479176,5.818226,5.952556e-09
22,C(hour)[T.22],22.873519,7.600906,3.009315,2.618559e-03
23,C(hour)[T.23],8.011718,7.814279,1.025266,3.052382e-01
24,C(day_of_week)[T.1],-61.929838,3.941216,-15.713384,1.278154e-55
25,C(day_of_week)[T.2],-17.956879,3.932433,-4.566353,4.964470e-06
26,C(day_of_week)[T.3],-21.325040,3.933193,-5.421814,5.903527e-08
27,C(day_of_week)[T.4],-26.587910,3.914274,-6.792552,1.103374e-11
28,C(day_of_week)[T.5],-147.510670,3.983781,-37.027805,1.511275e-299
29,C(day_of_week)[T.6],-155.256838,4.013646,-38.682247,0.000000e+00
30,C(severity_tier_numeric)[T.2],152.641208,2.837685,53.790749,0.000000e+00
31,C(severity_tier_numeric)[T.3],436.973414,2.720676,160.612078,0.000000e+00
32,C(borough)[T.BROOKLYN],26.913268,4.214244,6.386263,1.701956e-10
33,C(borough)[T.MANHATTAN],123.658850,4.132608,29.922716,1.742240e-196
34,C(borough)[T.QUEENS],-36.401243,4.463629,-8.155077,3.500648e-16
35,C(borough)[T.RICHMOND / STATEN ISLAND],-95.699116,6.572880,-14.559692,5.231100e-48
36,C(high_black_zip)[T.1],24.189224,4.445175,5.441681,5.281453e-08
37,median_income,0.000179,0.000049,3.672323,2.403908e-04
38,pct_white,-32.902871,11.855145,-2.775409,5.513523e-03
39,pct_black,143.341284,12.031610,11.913724,1.018286e-32
40,pct_hispanic,193.923727,10.071381,19.254930,1.413026e-82

In [85]:
model.columns = ["Predictors", "Coefficient", "Standard Error", "t", "p-value"]
model["Predictors"] = ["Intercept", "1 AM", "2 AM", "3 AM", "4 AM", "5 AM", "6 AM", "7 AM", "8 AM", "9 AM", "10 AM", "11 AM", "12 PM", "1 PM", "2 PM", "3 PM", "4 PM", "5 PM", "6 PM", "7 PM", "8 PM", "9 PM", "10 PM", "11 PM", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Severity Level: Medium", "Severity Level: Low", "Brooklyn", "Hanhattan", "Queens", "Richmond / Staten Island", "High Black ZIP", "Median Income", "White Percent", "Black Percent", "Hispanic Percent"]
model

,Predictors,Coefficient,Standard Error,t,p-value
0,Intercept,206.163649,11.960451,17.237113,1.487709e-66
1,1 AM,19.529311,8.177713,2.388114,1.693560e-02
2,2 AM,21.761760,8.526913,2.552127,1.070717e-02
3,3 AM,62.793767,8.802166,7.133899,9.774769e-13
4,4 AM,62.140589,9.015552,6.892599,5.487182e-12
5,5 AM,79.358833,9.152281,8.670935,4.303224e-18
6,6 AM,151.148118,8.872062,17.036414,4.677624e-65
7,7 AM,129.638154,8.329836,15.563110,1.350907e-54
8,8 AM,139.888649,7.743290,18.065789,6.385675e-73
9,9 AM,127.692992,7.400898,17.253716,1.116494e-66
10,10 AM,113.965386,7.311407,15.587339,9.250719e-55
11,11 AM,155.047400,7.273738,21.316054,9.307467e-101
12,12 PM,177.398343,7.265929,24.415094,1.515164e-131
13,1 PM,208.279441,7.276076,28.625241,5.205478e-180
14,2 PM,263.482059,7.246028,36.362275,5.672124e-289
15,3 PM,345.950813,7.259738,47.653345,0.000000e+00
16,4 PM,360.543389,7.300167,49.388376,0.000000e+00
17,5 PM,406.644280,7.314319,55.595647,0.000000e+00
18,6 PM,416.480243,7.329631,56.821444,0.000000e+00
19,7 PM,227.883861,7.336313,31.062450,1.481564e-211
20,8 PM,104.205915,7.394035,14.093241,4.296816e-45
21,9 PM,43.515537,7.479176,5.818226,5.952556e-09
22,10 PM,22.873519,7.600906,3.009315,2.618559e-03
23,11 PM,8.011718,7.814279,1.025266,3.052382e-01
24,Monday,-61.929838,3.941216,-15.713384,1.278154e-55
25,Tuesday,-17.956879,3.932433,-4.566353,4.964470e-06
26,Wednesday,-21.325040,3.933193,-5.421814,5.903527e-08
27,Thursday,-26.587910,3.914274,-6.792552,1.103374e-11
28,Friday,-147.510670,3.983781,-37.027805,1.511275e-299
29,Saturday,-155.256838,4.013646,-38.682247,0.000000e+00
30,Severity Level: Medium,152.641208,2.837685,53.790749,0.000000e+00
31,Severity Level: Low,436.973414,2.720676,160.612078,0.000000e+00
32,Brooklyn,26.913268,4.214244,6.386263,1.701956e-10
33,Hanhattan,123.658850,4.132608,29.922716,1.742240e-196
34,Queens,-36.401243,4.463629,-8.155077,3.500648e-16
35,Richmond / Staten Island,-95.699116,6.572880,-14.559692,5.231100e-48
36,High Black ZIP,24.189224,4.445175,5.441681,5.281453e-08
37,Median Income,0.000179,0.000049,3.672323,2.403908e-04
38,White Percent,-32.902871,11.855145,-2.775409,5.513523e-03
39,Black Percent,143.341284,12.031610,11.913724,1.018286e-32
40,Hispanic Percent,193.923727,10.071381,19.254930,1.413026e-82

In [86]:
output_path = "../outputs/tables/final/model_with_protected_variables.csv"
model.to_csv(output_path, index=False)

Pairwise Q1 vs Q4 tests by Tier Income Q

In [88]:
pairwise_test_income = pd.read_csv("../outputs/tables/raw/pairwise_q1_vs_q4_tests_by_tier_income_q.csv")
pairwise_test_income

,severity_tier,n_Q1_low,n_Q4_high,mean_Q1_low,mean_Q4_high,mean_diff_Q1_minus_Q4_sec,welch_ttest_p_value
0,High,22117,20012,475.389339,445.586898,29.802441,2.538069e-19
1,Medium,28797,32044,653.998264,594.812726,59.185537,3.907677e-40
2,Low,40117,36766,990.839619,850.691046,140.148573,2.731406e-102

In [91]:
pairwise_test_income.columns = ["Severity Tier", "n (Q1 Low)", "n (Q4 High)", "mean (Q1 Low)", "mean (Q4 High)", "Mean Difference: Q1 - Q4 (seconds)", "Welch t-test p-value"]
pairwise_test_income

,Severity Tier,n (Q1 Low),n (Q4 High),mean (Q1 Low),mean (Q4 High),Mean Difference: Q1 - Q4 (seconds),Welch t-test p-value
0,High,22117,20012,475.389339,445.586898,29.802441,2.538069e-19
1,Medium,28797,32044,653.998264,594.812726,59.185537,3.907677e-40
2,Low,40117,36766,990.839619,850.691046,140.148573,2.731406e-102

In [92]:
output_path = "../outputs/tables/final/pairwise_q1_vs_q4_tests_by_tier_income_q.csv"
pairwise_test_income.to_csv(output_path, index=False)

Pairwise Tests by Tier High Black Zip

In [93]:
pairwise_test_high_black_zip = pd.read_csv("../outputs/tables/raw/pairwise_tests_by_tier_high_black_zip.csv")
pairwise_test_high_black_zip

,severity_tier,n_lowBlackZIP,n_highBlackZIP,mean_response_lowBlackZIP_sec,mean_response_highBlackZIP_sec,mean_difference_highBlack_minus_lowBlack_sec,welch_ttest_p_value,mannwhitney_p_value,welch_ttest_p_value_fdr,mannwhitney_p_value_fdr
0,High,42358,44212,444.339109,479.640256,35.301147,4.742948e-56,1.575196e-121,4.742948e-56,1.575196e-121
1,Medium,67175,57474,587.958496,649.047378,61.088881,5.270265e-92,3.403515e-167,7.905397e-92,5.105273e-167
2,Low,74571,77693,827.403870,959.819984,132.416114,3.740520e-199,0.000000e+00,1.122156e-198,0.000000e+00

In [94]:
pairwise_test_high_black_zip.columns = ["Severity Tier", "n (Low Black ZIP)", "n (High Black ZIP)", "Mean Reasponse for Low Black ZIP (sec)", "Mean Response for High Black ZIP (sec)", "Mean Difference: High Black ZIP - Low Black ZIP (sec)", "Welch t-test p-value", "Mann-Whitney p-value", "Welch t-test p-value (FDR)", "Mann-Whitney p-value (FDR)"]
pairwise_test_high_black_zip

,Severity Tier,n (Low Black ZIP),n (High Black ZIP),Mean Reasponse for Low Black ZIP (sec),Mean Response for High Black ZIP (sec),Mean Difference: High Black ZIP - Low Black ZIP (sec),Welch t-test p-value,Mann-Whitney p-value,Welch t-test p-value (FDR),Mann-Whitney p-value (FDR)
0,High,42358,44212,444.339109,479.640256,35.301147,4.742948e-56,1.575196e-121,4.742948e-56,1.575196e-121
1,Medium,67175,57474,587.958496,649.047378,61.088881,5.270265e-92,3.403515e-167,7.905397e-92,5.105273e-167
2,Low,74571,77693,827.403870,959.819984,132.416114,3.740520e-199,0.000000e+00,1.122156e-198,0.000000e+00

In [96]:
output_path = "../outputs/tables/final/pairwise_tests_by_tier_high_black_zip.csv"
pairwise_test_high_black_zip.to_csv(output_path, index=False)